[[language]]
name = "python"
language-servers = [ { name = "pyright" } ]
auto-format = true
formatter = { command = "black", args = ["-", "-q"] }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
